name = "memos-worker"
compatibility_date = "2026-07-01"
main = "src/index.js"

[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

# D1 数据库
[[d1_databases]]
binding = "DB"
database_id = "22832d17-1162-4a74-b199-7257ca859752"
database_name = "memos"

# KV 命名空间
[[kv_namespaces]]
binding = "NOTES_KV"
id = "4473c9e2041e42d3907bab869a1efb97"

# R2 存储桶（桶名memos，绑定名R2）
[[r2_buckets]]
binding = "R2"
bucket_name = "memos"
preview_bucket_name = "memos-preview"

# 站点全局变量
[vars]
SITE_NAME = "我的备忘录"
ALLOW_REGISTER = "true"
MAX_UPLOAD_SIZE = "10"
